### ISSUE TITLE
I can't download the 2016 file

### ISSUE THREAD

**Issue by CasterZhen** [H1emu/h1emu-launcher#11]
It say
![1652872407543](https://user-images.githubusercontent.com/105789371/169027625-7b303d19-0d05-4c33-abe5-5a853381314b.jpg)

**Comment by CasterZhen** [comment]
An item with the same key has already been added. key 30182

**Comment by QuentinGruber** [comment]
Hey @CasterZhen I think this problem is from steam servers, try again in an hour or two. @Eavilaswayce Maybe we should change the error log to be more explanatory?

**Comment by CasterZhen** [comment]
I wanna play H1Z1 ><, I am Taiwanese, and I very love this game!!!!!!!!!!!

**Comment by QuentinGruber** [comment]
> I wanna play H1Z1 ><, I am Taiwanese, and I very love this game!!!!!!!!!!!

Don't worry you'll be able to play it 😄, it's just a temporary problem

**Comment by CasterZhen** [comment]
But yesterday I press download 2016 version, the same log jump out....

**Comment by CasterZhen** [comment]
> > I wanna play H1Z1 ><, I am Taiwanese, and I very love this game!!!!!!!!!!!
> 
> Don't worry you'll be able to play it 😄, it's just a temporary problem

 STILL THE SAME :(

**Comment by CasterZhen** [comment]
Is My computer problem?

**Comment by CasterZhen** [comment]
Connecting to Steam3... Done!
Logging 'awesomegarage35' into Steam3...Disconnected from Steam
This account is protected by Steam Guard.
Please enter the authentication code sent to your email address: Retrying Steam3 connection... Done!
Logging 'awesomegarage35' into Steam3... Done!
Using Steam3 suggested CellID: 9
Got 39 licenses for account!
Download failed to due to an unhandled exception: 已經加入含有相同索引鍵的項目。
Failed to retrieve content server list: 已取消作業。
Got session token!
Got Machine Auth: ssfn6277173463991625993 0 2048 2048
Disconnected from Steam

**Comment by CasterZhen** [comment]
> It's really hard to know where this error is coming from, since I can't reproduce it I simply can't debug it.
> 
> Are you able to try and use the official DepotDownloader and see if you get the same error?

Can you control my computer help me out? Use teamviewer I give you code~

**Comment by CasterZhen** [comment]
Maybe I should delete the h1z1 in steam? Or delete something?

**Comment by QuentinGruber** [comment]
> Maybe I should delete the h1z1 in steam? Or delete something?

It's still not working ? Is your steam profile public ? So we can check which games do you own ?

**Comment by QuentinGruber** [comment]
Just in case have you tried https://github.com/H1emu/H1DepotDownloader ? Even if it should be the same result.

**Comment by CasterZhen** [comment]
> 

Yes my account is open~you can take a look
awesomegarage35 (MY ID)

**Comment by CasterZhen** [comment]
> Just in case have you tried https://github.com/H1emu/H1DepotDownloader ? Even if it should be the same result.

I tried yesterday.... It say
Connecting to Steam3... Done!
Logging 'awesomegarage35' into Steam3...Disconnected from Steam
This account is protected by Steam Guard.
Please enter the authentication code sent to your email address: Retrying Steam3 connection... Done!
Logging 'awesomegarage35' into Steam3... Done!
Using Steam3 suggested CellID: 9
Got 39 licenses for account!
Download failed to due to an unhandled exception: 已經加入含有相同索引鍵的項目。
Failed to retrieve content server list: 已取消作業。
Got session token!
Got Machine Auth: ssfn3067795779543180601 0 2048 2048
Disconnected from Steam

**Comment by Eavilaswayce** [comment]
Do you want to dm on Discord? We can use TeamViewer

**Comment by Eavilaswayce** [comment]
I have solved his issue, but the bug still remains.

The error seems to be account specific for some reason, my account works to download the game, but his doesn't. I'm not sure why.

**Comment by Eavilaswayce** [comment]
Fixed on 2.4.8
