### ISSUE TITLE
Key has been used

### ISSUE THREAD

**Issue by Fives515** [H1emu/h1emu-launcher#14]
I followed the tutorial for installing the game, but after logging in and pressing to download either version of the game, it claims that the key has already been used and goes back to the login section.

What I have done:
- Followed the tutorial
- Added the account key to the launcher
- Also tried to go through downloading the older version manually but also did not work.

![Screenshot 2022-07-27 171308](https://user-images.githubusercontent.com/100932297/181297097-bd427c4d-80a1-406f-8605-99a8e28179e6.png)

**Comment by QuentinGruber** [comment]
https://github.com/H1emu/h1emu-launcher/issues/11 duplicate
