### ISSUE TITLE
Launcher use too much ram

### ISSUE THREAD

**Issue by QuentinGruber** [H1emu/h1emu-launcher#15]
95% of the ram used is "unmanaged memory" idk what's that? pictures ? node files loaded and keeped in memory ?

**Comment by Eavilaswayce** [comment]
Been trying to look into this, but I don't see anything. The launcher uses about ~250mb RAM while open, with and without the image carousel operating. Were you doing anything with the launcher when you noticed that usage?

**Comment by QuentinGruber** [comment]
![image](https://user-images.githubusercontent.com/47059878/209799583-5ac8ddfd-e63a-4b99-9fc9-fd62a062801d.png)
@Eavilaswayce By using jetbrain dotmemory i found out about these 95% of the ram used is "unmanaged memory", idk if it is something we can fix or not or even if this is a normal behavior

**Comment by QuentinGruber** [comment]
Could be somehow node binaries ? that you store on memory ?

**Comment by Eavilaswayce** [comment]
I think this is 95% of the ~500mb of RAM that the launcher has used in total from opening that is unmanaged? Like it's not 95% of the computers RAM, at least that's what I thought originally. In this case I don't think it's an issue as of right now

**Comment by QuentinGruber** [comment]
![image](https://user-images.githubusercontent.com/47059878/211394070-409bb18b-0fab-43cf-891f-881411700db3.png)
Well i just tried to run an hello world WPF and it still have this 95% unmanaged memory usage, I guess we can't do much about it
