### ISSUE TITLE
bug ?

### ISSUE THREAD

**Issue by IRStaten** [H1emu/h1emu-launcher#16]
cant get past trying to launch the launcher, i get this 

"microsoft.windowsdesktop.app', version '6.0.0'

i already have 6.0.0 installed...
does it not detect .net 6.0.0 ?

**Comment by Eavilaswayce** [comment]
Are you sure you installed specifically the .NET Desktop Runtime? Found here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.12-windows-x64-installer

I suggest downloading that and installing it anyway just in case you installed something else my mistake
