### ISSUE TITLE
Reinstalling server files Failing

### ISSUE THREAD

**Issue by Mister-Wizz** [H1emu/h1emu-launcher#24]
Hello, I am having troubles getting the game to launch in the single player version. I am trying to reinstall server files and am getting "Access to the path 'node.exe' is denied.". I have tried to completely wipe all the files off my computer and reinstalling everything again and keep getting the same issue. I just found this ability to play this game again a few days ago and am very excited to play again. I had near 4000 hours into this game when they shut it down. would love to play in single player mode. Thank you in advance for any help

**Comment by Eavilaswayce** [comment]
Try running the program as Administrator, and check for any processes in Task Manager called "node.exe" and end them if they exist.

**Comment by Mister-Wizz** [comment]
Thank you for your response. I will give it a try.
