### ISSUE TITLE
Error when starting launcher.

### ISSUE THREAD

**Issue by QuentinGruber** [H1emu/h1emu-launcher#25]
https://github.com/QuentinGruber/h1z1-server/issues/1347 by @Timpa19

**Comment by Timpa19** [comment]
Im new to this platform so i dont really know how this works, just made an account to submit my  issue.

**Comment by QuentinGruber** [comment]
> Im new to this platform so i dont really know how this works, just made an account to submit my issue.

It's ok i've just moved your issue to the right repository :)

**Comment by Timpa19** [comment]
okay so I don't have to post it again? :)

**Comment by Timpa19** [comment]
![F1BE01D9-1836-4608-84B5-53871D9B99DF](https://user-images.githubusercontent.com/124501348/216822312-82ec8ae5-f5f1-40c0-a7c9-3bed0bc34923.jpeg)

I get this error message when trying to start launcher. Never had a problem up until yesterday when it just randomly started. Tried uninstalling and installing everything a bunch of times and messing with my files but i cant get it to work.

**Comment by QuentinGruber** [comment]
> okay so I don't have to post it again? :)

there was a link to the old one 😄

**Comment by Timpa19** [comment]
> > okay so I don't have to post it again? :)
> 
> there was a link to the old one 😄 

Haha i see! I saw that you updated the launcher about 16 hours ago and before that I had no problems what so ever. So I think something happened with the new update on the launcher. is there anyway one can use a old version?

**Comment by Timpa19** [comment]
I think it might have something to do with this, everyone is talking about gif files being made to resource, i dont know how that works but thats all that is mentionen with this kind of problem https://github.com/XamlAnimatedGif/WpfAnimatedGif/issues/62

**Comment by QuentinGruber** [comment]
> 

https://github.com/H1emu/h1emu-launcher/releases you can download old version there and refuse update

**Comment by Timpa19** [comment]
using the previous launcher update worked without problems, so its something that has been added with the new launcher, lets hope this does not continue with later updates of the launcher aswell! Maybe when u have time, take a look at the gif file thing i mentioned, I might be off on the wrong foot but i do think its close to the problem. Thank you for your time!

**Comment by Eavilaswayce** [comment]
Hi Timpa19, would you mind sending me a dm on Discord? You can see me as the user Eavilaswayce, I would like to try and find out more about this issue, thanks.
