### ISSUE TITLE
hello !!je ne recois pas le mail avec le code que puis faire

### ISSUE THREAD

**Issue by Sanpapaya** [H1emu/h1emu-launcher#28]
je ne reçois pas le mail avec le code , que puis faire , pourtant j ai steam guard a deux facteur

**Comment by QuentinGruber** [comment]
Bonne question c'est lier à steam pas nous, je ne sais pas trop comment t'aider :(

**Comment by Sanpapaya** [comment]
Ok merci d avoir répondu ,mais   erreur résolu !!

De : ***@***.***>
Envoyé le :samedi 15 avril 2023 14.34
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [H1emu/h1emu-launcher] hello !!je ne recois pas le mail avec le code que puis faire (Issue #28)


Bonne question c'est lier à steam pas nous, je ne sais pas trop comment t'aider :(
