### ISSUE TITLE
Use too much GPU

### ISSUE THREAD

**Issue by QuentinGruber** [H1emu/h1emu-launcher#30]

**Comment by QuentinGruber** [comment]
@Eavilaswayce it's the carrousel who use a decent amount of the gpu like literraly the red loading bar

**Comment by Eavilaswayce** [comment]
How do you know this? The red loading bar is just a DoubleAnimation which there are like 100 of in the launcher so I don't see why this one would be any different :/

I did, however, read somewhere that the use of DropShadow effects in WPF increases GPU usage a lot for some reason, this could be it possibly.

**Comment by QuentinGruber** [comment]
> How do you know this? The red loading bar is just a DoubleAnimation which there are like 100 of in the launcher so I don't see why this one would be any different :/
> 
> I did, however, read somewhere that the use of DropShadow effects in WPF increases GPU usage a lot for some reason, this could be it possibly.

Well open your task manager and look how much gpu is used, 30+% when the carrousel is running and 0 when i put the mouse on it ( so it stop ).

**Comment by Eavilaswayce** [comment]
Damn you're right, for me it uses ~18% GPU and then when the carousel stops it's 0%. Wonder if it's possible to limit GPU usage on a WPF app?

**Comment by QuentinGruber** [comment]
Maybe we could just remove that animation ? @Eavilaswayce  Yeah it looks cool but for what it cost :sweat_smile:

**Comment by QuentinGruber** [comment]
I just took a look @Eavilaswayce. The problem is that the animation is rendered for every px between 0 and the width of the rectangle. If there was a way to make the animation render only every 5 pixels, it would improve performance and no one would notice a difference.

**Comment by QuentinGruber** [comment]
> I just took a look @Eavilaswayce. The problem is that the animation is rendered for every px between 0 and the width of the rectangle. If there was a way to make the animation render only every 5 pixels, it would improve performance and no one would notice a difference.

you can test it by changing the time the animation take with more time the animation have less px to travel per sec and so consume less gpu
