### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by karnivar** [H1emu/h1emu-launcher#31]
When trying to enter the server, it does not let me access, in this last update, it gives me something as if I did not identify myself and I have already played before.Any solution?

**Comment by QuentinGruber** [comment]
> When trying to enter the server, it does not let me access, in this last update, it gives me something as if I did not identify myself and I have already played before.Any solution?

You need to register on discord to have access to online servers ( it's free ) just look at help channel or info channels in the discord https://discord.com/invite/RM6jNkj
