### ISSUE TITLE
launcher!

### ISSUE THREAD

**Issue by Madst2003** [H1emu/h1emu-launcher#34]
my launcher keeps saying, you need to download a diffent version but it keeps saying that so i cant play!! and i cant find out what to do!!
![lort](https://github.com/H1emu/h1emu-launcher/assets/163155871/cb903d0c-4841-40eb-bc0c-9cbe9a999945)

**Comment by QuentinGruber** [comment]
Hey @Madst2003 did you change the path to your game directory ? If you want more direct support go to #help on our discord :cowboy_hat_face:
