### ISSUE TITLE
DİSCORD KEY

### ISSUE THREAD

**Issue by Swane11** [H1emu/h1emu-launcher#38]
Hello, we can't get a Discord key code, and I can't log in to the game without the key code because we are connecting from Turkey. In recent events, Discord has been closed and access has been blocked in Turkey. Can you help me with this issue?
![Ekran Alıntısı](https://github.com/user-attachments/assets/d1d304bd-e7e8-4429-b8fd-56f135de2bc2)

**Comment by QuentinGruber** [comment]
Sorry use a vpn
